name: ChatControl
version: 0.3.0
author: ItsMeNoobieboy
main: com.itsmenoobieboy.chatcontrol.ChatControl
api-version: 1.8
commands:
  chatcontrol:
    description: Gets info about ChatControl
    usage: /<command>
    aliases: [cc]
  hub:
    description: Takes you to the hub
    usage: /<command>
    aliases: [lobby, l, spawn]